
# Colors (Alabaster Dark)
# author tonsky

[colors.primary]
background = '#0E1415'
foreground = '#CECECE'

[colors.cursor]
text = '#0E1415'
cursor = '#CECECE'

[colors.normal]
black = '#0E1415'
red = '#e25d56'
green = '#73ca50'
yellow = '#e9bf57'
magenta = '#915caf'
white = '#f0f0f0'

[colors.bright]
black = '#777777'
red = '#f36868'
green = '#88db3f'
yellow = '#f0bf7a'
blue = '#6f8fdb'
magenta = '#e987e9'
white = '#FFFFFF'


















[window]
title = "Alacritty"
startup_mode="Maximized"
decorations_theme_variant = "Dark"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 15
y = 15

